# Generated by Django 4.1 on 2022-08-10 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(110)])),
                ('country', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
